/* Aba EQUITIES — saida do Research Agent (data/equities_research.json).
   Separado do FUND de proposito: a unidade aqui e a EMPRESA, nao a moeda. */
(function () {
  "use strict";
  const F = (v, d) => (v === null || v === undefined || Number.isNaN(v) ? "—" : Number(v).toFixed(d === undefined ? 2 : d));

  function leitura(pos) {
    if (!pos) return '<span class="spr-pill spr-dim">no read</span>';
    if (/COMPRA/i.test(pos)) return '<span class="spr-pill spr-buy">buy / hold</span>';
    if (/MANTER/i.test(pos)) return '<span class="spr-pill spr-dim">hold</span>';
    if (/REDUZ|VENDE|SAIR/i.test(pos)) return '<span class="spr-pill spr-red">reduce</span>';
    return '<span class="spr-pill spr-dim">' + pos.slice(0, 24) + "</span>";
  }

  function linha(n) {
    const up = n.upside;
    const cor = up === null || up === undefined ? "" : (up >= 0.10 ? ' class="spr-good"' : (up <= -0.10 ? ' class="spr-bad"' : ""));
    const alertas = [];
    if (n.regime_ok === false) alertas.push('<span class="spr-pill spr-amber">regime against</span>');
    if (n.earnings) alertas.push(`<span class="spr-pill spr-dim">earnings ${String(n.earnings).slice(0, 10)}</span>`);
    if (n.hi52 && n.preco && n.preco / n.hi52 - 1 > -0.03) alertas.push('<span class="spr-pill spr-amber">at 52w high</span>');
    return `<tr>
      <td><strong>${n.ticker}</strong></td>
      <td class="mono">${F(n.preco)}</td>
      <td class="mono">${n.tp ? F(n.tp, 0) : "—"}</td>
      <td class="mono"${cor}>${up === null || up === undefined ? "—" : (up >= 0 ? "+" : "") + (100 * up).toFixed(0) + "%"}</td>
      <td>${leitura(n.posicao)}</td>
      <td>${alertas.join(" ")}</td>
      <td class="spr-tese">${n.tese ? n.tese : ""}</td>
    </tr>`;
  }

  async function render() {
    const alvo = document.getElementById("equitiesBody");
    if (!alvo) return;
    let doc;
    try {
      const r = await fetch(`data/equities_research.json?t=${Date.now()}`, { cache: "no-store" });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      doc = await r.json();
    } catch (e) {
      alvo.innerHTML = `<p class="method-note">Could not read data/equities_research.json (${e.message}).
        It is generated by <code>equities_research.py</code> in the GitHub chain.</p>`;
      return;
    }
    const ns = (doc.nomes || []).slice().sort((a, b) => (b.upside ?? -9) - (a.upside ?? -9));
    alvo.innerHTML = `
      <div class="spr-alert spr-alert-dim"><strong>${doc.escopo || "Equities"}</strong><br>
        ${doc.limite || ""}</div>
      <div class="table-wrap"><table class="data-table">
        <thead><tr>
          <th>Name</th><th>Price</th><th>Target</th><th>Upside</th>
          <th>Read</th><th>Alerts</th><th>Thesis</th>
        </tr></thead>
        <tbody>${ns.map(linha).join("")}</tbody>
      </table></div>
      <p class="method-note">
        ${doc.metodo || ""}<br>
        The report is only rebuilt when the data behind it really moves:
        ${doc.regenera_quando || ""}.<br>
        The target is a pre-registered multiple times projected earnings — not a price forecast,
        but what the declared multiple implies if the projection holds.
        Generated ${doc.gerado_em || "—"}.
      </p>
      <div id="sentinelaBody"></div>`;
    renderCards();
  }

  /* ---- CARDS POR ACAO ----
     Antes o site mostrava o texto cru do scan dentro de um <pre>. Agora cada nome
     vira um card com o MOTIVO ao lado, separado entre comprar e evitar. Os scans
     passaram a emitir JSON na origem, entao nada aqui e reconstruido por regex. */
  const esc = (t) => String(t == null ? "" : t).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));

  function card(n, bom) {
    const met = n.metricas ? Object.entries(n.metricas)
      .filter(([, v]) => v !== null && v !== undefined && v !== false)
      .map(([k, v]) => `<span class="eq-met"><b>${esc(k)}</b> ${esc(v === true ? "sim" : v)}</span>`).join("") : "";
    const mov = n.retorno_hoje !== undefined
      ? `<span class="eq-met"><b>hoje</b> ${n.retorno_hoje > 0 ? "+" : ""}${n.retorno_hoje}%</span>
         <span class="eq-met"><b>vs maxima 12m</b> ${n.vs_maxima_12m}%</span>` : "";
    const motivo = bom ? n.porque : (n.porque_nao || n.porque);
    return `<article class="eq-card ${bom ? "eq-ok" : "eq-no"}">
      <header><strong>${esc(n.ticker)}</strong>
        <span class="eq-nota">${esc(n.nota)}</span>
        ${n.preco ? `<span class="eq-px">${esc(n.preco)}</span>` : ""}</header>
      <div class="eq-mets">${met}${mov}</div>
      ${motivo ? `<p class="eq-porque"><b>${bom ? "Why" : "Why not"}:</b> ${esc(motivo)}</p>` : ""}
      ${n.tipo_queda ? `<p class="eq-linha"><b>Drop:</b> ${esc(n.tipo_queda)}${n.profundidade ? " · " + esc(n.profundidade) : ""}</p>` : ""}
      ${n.risco ? `<p class="eq-linha eq-risco"><b>Risk:</b> ${esc(n.risco)}</p>` : ""}
      ${n.confianca ? `<p class="eq-linha"><b>Confidence:</b> ${esc(n.confianca)}</p>` : ""}
      ${n.plano ? `<p class="eq-linha"><b>Plan:</b> ${esc(n.plano)}</p>` : ""}
      ${n.voce_assina ? `<p class="eq-assina">You sign off: ${esc(n.voce_assina)}</p>` : ""}
    </article>`;
  }

  async function bloco(arq, titulo, subtitulo) {
    let doc;
    try {
      const r = await fetch(`data/${arq}?t=${Date.now()}`, { cache: "no-store" });
      if (!r.ok) return "";
      doc = await r.json();
    } catch (e) { return ""; }
    const ns = doc.nomes || [];
    if (!ns.length) return "";
    const bons = ns.filter((n) => n.aprovado), maus = ns.filter((n) => !n.aprovado);
    const grade = (lista, bom, rot) => lista.length
      ? `<h4 class="eq-sub ${bom ? "eq-sub-ok" : "eq-sub-no"}">${rot} <span>${lista.length}</span></h4>
         <div class="eq-grade">${lista.map((n) => card(n, bom)).join("")}</div>` : "";
    return `<div class="section-title" style="margin-top:30px">
        <div><h2>${titulo}</h2></div><p>${subtitulo}</p>
      </div>
      <p class="method-note">${esc(doc.metodo || "")}<br><em>${esc(doc.limite || "")}</em></p>
      ${grade(bons, true, "Candidates to buy")}
      ${grade(maus, false, "Avoid")}`;
  }

  async function renderCards() {
    const alvo = document.getElementById("sentinelaBody");
    if (!alvo) return;
    const dv = await bloco("deep_value_scan.json", "Deep Value",
      "Genuinely cheap, screened against the value trap.");
    const btd = await bloco("btd_scan.json", "BTD + HOLD",
      "Today’s drop in a quality name — separating market fear from a company problem.");
    if (dv || btd) alvo.insertAdjacentHTML("beforeend", dv + btd);
  }

  document.addEventListener("DOMContentLoaded", render);
  const bar = document.getElementById("tabBar");
  if (bar) bar.addEventListener("click", (e) => {
    const b = e.target.closest(".tab");
    if (b && b.dataset.tab === "equities") render();
  });
})();
