/* Aba EQUITIES — saida do Research Agent (data/equities_research.json).
   Separado do FUND de proposito: a unidade aqui e a EMPRESA, nao a moeda. */
(function () {
  "use strict";
  const F = (v, d) => (v === null || v === undefined || Number.isNaN(v) ? "—" : Number(v).toFixed(d === undefined ? 2 : d));
  const numero = (v) => (v === null || v === undefined || v === "") ? null : (Number.isFinite(Number(v)) ? Number(v) : null);

  function leitura(pos) {
    if (!pos) return '<span class="spr-pill spr-dim">no read</span>';
    if (/COMPRA/i.test(pos)) return '<span class="spr-pill spr-buy">buy / hold</span>';
    if (/MANTER/i.test(pos)) return '<span class="spr-pill spr-dim">hold</span>';
    if (/REDUZ|VENDE|SAIR/i.test(pos)) return '<span class="spr-pill spr-red">reduce</span>';
    return '<span class="spr-pill spr-dim">' + pos.slice(0, 24) + "</span>";
  }

  function linha(n) {
    const up = n.upside;
    const cor = up === null || up === undefined ? "" : (up >= 0.10 ? ' class="spr-good"' : (up <= -0.10 ? ' class="spr-bad"' : ""));
    const alertas = [];
    if (n.regime_ok === false) alertas.push('<span class="spr-pill spr-amber">regime against</span>');
    if (n.earnings) alertas.push(`<span class="spr-pill spr-dim">earnings ${String(n.earnings).slice(0, 10)}</span>`);
    if (n.hi52 && n.preco && n.preco / n.hi52 - 1 > -0.03) alertas.push('<span class="spr-pill spr-amber">at 52w high</span>');
    return `<tr>
      <td><strong>${n.ticker}</strong></td>
      <td class="mono">${F(n.preco)}</td>
      <td class="mono">${n.tp ? F(n.tp, 0) : "—"}</td>
      <td class="mono"${cor}>${up === null || up === undefined ? "—" : (up >= 0 ? "+" : "") + (100 * up).toFixed(0) + "%"}</td>
      <td>${leitura(n.posicao)}</td>
      <td>${alertas.join(" ")}</td>
      <td class="spr-tese">${n.tese ? n.tese : ""}</td>
    </tr>`;
  }

  async function render() {
    const alvo = document.getElementById("equitiesBody");
    if (!alvo) return;
    let doc;
    try {
      const r = await fetch(`data/equities_research.json?t=${Date.now()}`, { cache: "no-store" });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      doc = await r.json();
    } catch (e) {
      alvo.innerHTML = `<p class="method-note">Could not read data/equities_research.json (${e.message}).
        It is generated by <code>equities_research.py</code> in the GitHub chain.</p>`;
      return;
    }
    const ns = (doc.nomes || []).slice().sort((a, b) => (b.upside ?? -9) - (a.upside ?? -9));
    alvo.innerHTML = `
      <div class="spr-alert spr-alert-dim"><strong>${doc.escopo || "Equities"}</strong><br>
        ${doc.limite || ""}</div>
      <div class="table-wrap"><table class="data-table">
        <thead><tr>
          <th>Name</th><th>Price</th><th>Target</th><th>Upside</th>
          <th>Read</th><th>Alerts</th><th>Thesis</th>
        </tr></thead>
        <tbody>${ns.map(linha).join("")}</tbody>
      </table></div>
      <p class="method-note">
        ${doc.metodo || ""}<br>
        The report is only rebuilt when the data behind it really moves:
        ${doc.regenera_quando || ""}.<br>
        The target is a pre-registered multiple times projected earnings — not a price forecast,
        but what the declared multiple implies if the projection holds.
        Generated ${doc.gerado_em || "—"}.
      </p>
      <div id="sentinelaBody"></div>`;
    renderCards();
  }

  /* ---- CARDS POR ACAO ----
     Antes o site mostrava o texto cru do scan dentro de um <pre>. Agora cada nome
     vira um card com o MOTIVO ao lado, separado entre comprar e evitar. Os scans
     passaram a emitir JSON na origem, entao nada aqui e reconstruido por regex. */
  /* Ficha da empresa: de onde vem o numero e onde ler mais. Carregada uma vez e
     compartilhada por todos os componentes — 94 empresas num arquivo so. */
  let FICHAS = null;
  async function fichas() {
    if (FICHAS !== null) return FICHAS;
    try {
      const r = await fetch(`data/empresas.json?t=${Date.now()}`, { cache: "no-store" });
      FICHAS = r.ok ? await r.json() : { empresas: {} };
    } catch (e) { FICHAS = { empresas: {} }; }
    return FICHAS;
  }

  function fichaHTML(tk) {
    const d = FICHAS && FICHAS.empresas ? FICHAS.empresas[tk] : null;
    if (!d) return "";
    const links = [];
    if (d.site) links.push(`<a href="${esc(d.site)}" target="_blank" rel="noopener">Company site</a>`);
    if (d.site_ri) links.push(`<a href="${esc(d.site_ri)}" target="_blank" rel="noopener">Investor relations</a>`);
    links.push(`<a href="https://finance.yahoo.com/quote/${encodeURIComponent(tk)}" target="_blank" rel="noopener">Yahoo Finance</a>`);
    if (!/\./.test(tk)) links.push(`<a href="https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&ticker=${encodeURIComponent(tk)}&type=10-K" target="_blank" rel="noopener">SEC filings</a>`);
    const meta = [d.setor, d.industria, d.pais,
                  d.funcionarios ? Number(d.funcionarios).toLocaleString() + " employees" : null]
                 .filter(Boolean).map((x) => `<span class="eq-met">${esc(x)}</span>`).join("");
    const news = (d.noticias || []).map((n) =>
      `<li><a href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.titulo)}</a>
       <em>${esc(n.fonte || "")}</em></li>`).join("");
    return `<details class="eq-ficha"><summary>Company file &amp; sources</summary>
      <div class="eq-ficha-body">
        ${d.nome ? `<p class="eq-nome">${esc(d.nome)}</p>` : ""}
        <div class="eq-mets">${meta}</div>
        ${d.o_que_faz ? `<p class="eq-faz">${esc(d.o_que_faz)}</p>` : ""}
        <p class="eq-links">${links.join(" · ")}</p>
        ${news ? `<p class="eq-linha"><b>Recent coverage</b></p><ul class="eq-news">${news}</ul>` : ""}
        <p class="eq-fonte">Profile and news: Yahoo Finance, read ${esc(d.perfil_em || "—")}.
        ${d.noticias_em ? "Coverage " + esc(d.noticias_em) + "." : ""}</p>
      </div></details>`;
  }

  const esc = (t) => String(t == null ? "" : t).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]));

  function motivoPadrao(n, bom, tipo) {
    if (bom) return n.porque;
    if (tipo === "fornecedores") {
      const r = numero(n.retorno_hoje);
      if (r === null) return "Variação diária indisponível; sem setup até a próxima leitura válida.";
      if (r < 0) return `Queda de ${Math.abs(r).toFixed(1)}%, abaixo do gatilho de 3%.`;
      return `Alta de ${r.toFixed(1)}%; não houve queda para acionar o gatilho.`;
    }
    if (tipo === "deep-value" && Array.isArray(n.reprovacoes) && n.reprovacoes.length) {
      return `Reprovada por ${n.reprovacoes.join(", ")}.`;
    }
    if (tipo === "deep-value" && /NET CASH|balan[cç]o ok/i.test(n.porque_nao || "")) {
      return "Reprovada pela peneira anti-armadilha; revise lucro, fluxo de caixa e endividamento.";
    }
    return n.porque_nao || n.porque;
  }

  function card(n, bom, tipo) {
    const met = n.metricas ? Object.entries(n.metricas)
      .filter(([, v]) => v !== null && v !== undefined && v !== false)
      .map(([k, v]) => `<span class="eq-met"><b>${esc(k)}</b> ${esc(v === true ? "sim" : v)}</span>`).join("") : "";
    const ret = numero(n.retorno_hoje), maxima = numero(n.vs_maxima_12m);
    const mov = (ret !== null || maxima !== null)
      ? `${ret === null ? "" : `<span class="eq-met"><b>hoje</b> ${ret > 0 ? "+" : ""}${ret.toFixed(1)}%</span>`}
         ${maxima === null ? "" : `<span class="eq-met"><b>vs máxima 12m</b> ${maxima > 0 ? "+" : ""}${maxima.toFixed(0)}%</span>`}` : "";
    const motivo = motivoPadrao(n, bom, tipo);
    return `<article class="eq-card ${bom ? "eq-ok" : "eq-no"}">
      <header><strong>${esc(n.ticker)}</strong>
        <span class="eq-nota">${esc(n.nota)}</span>
        ${n.preco ? `<span class="eq-px">${esc(n.preco)}</span>` : ""}</header>
      <div class="eq-mets">${met}${mov}</div>
      ${motivo ? `<p class="eq-porque"><b>${bom ? "Why" : "Why not"}:</b> ${esc(motivo)}</p>` : ""}
      ${n.tipo_queda ? `<p class="eq-linha"><b>Drop:</b> ${esc(n.tipo_queda)}${n.profundidade ? " · " + esc(n.profundidade) : ""}</p>` : ""}
      ${n.risco ? `<p class="eq-linha eq-risco"><b>Risk:</b> ${esc(n.risco)}</p>` : ""}
      ${n.confianca_status ? `<p class="eq-linha"><b>Convicção:</b> ${esc(n.confianca_status)}</p>`
        : n.confianca ? `<p class="eq-linha"><b>Convicção:</b> ${esc(n.confianca)}</p>` : ""}
      ${n.plano ? `<p class="eq-linha"><b>Plan:</b> ${esc(n.plano)}</p>` : ""}
      ${n.voce_assina ? `<p class="eq-assina">You sign off: ${esc(n.voce_assina)}</p>` : ""}
      ${fichaHTML(n.ticker)}
    </article>`;
  }

  async function bloco(arq, titulo, subtitulo, tipo, rotulos) {
    let doc;
    try {
      const r = await fetch(`data/${arq}?t=${Date.now()}`, { cache: "no-store" });
      if (!r.ok) return "";
      doc = await r.json();
    } catch (e) { return ""; }
    const ns = doc.nomes || [];
    if (!ns.length) return "";
    const bons = ns.filter((n) => n.aprovado), maus = ns.filter((n) => !n.aprovado);
    const grade = (lista, bom, rot) => lista.length
      ? `<h4 class="eq-sub ${bom ? "eq-sub-ok" : "eq-sub-no"}">${rot} <span>${lista.length}</span></h4>
         <div class="eq-grade">${lista.map((n) => card(n, bom, tipo)).join("")}</div>` : "";
    return `<div class="section-title" style="margin-top:30px">
        <div><h2>${titulo}</h2></div><p>${subtitulo}</p>
      </div>
      <p class="method-note">${esc(doc.metodo || "")}<br><em>${esc(doc.limite || "")}</em></p>
      ${grade(bons, true, rotulos[0])}
      ${grade(maus, false, rotulos[1])}`;
  }

  /* Revisao de estimativas — o unico sinal fundamental que sobreviveu aos testes de
     equities da casa. Nao vira card por nome: a leitura util e o RANKING e o setor. */
  async function blocoRevisoes() {
    let d;
    try {
      const r = await fetch(`data/revisoes.json?t=${Date.now()}`, { cache: "no-store" });
      if (!r.ok) return "";
      d = await r.json();
    } catch (e) { return ""; }
    if (!d.cima || !d.cima.length) return "";
    const linha = (n) => `<tr>
      <td><strong>${esc(n.ticker)}</strong></td>
      <td class="eq-setor">${esc(n.setor || "")}</td>
      <td class="mono">${n.preco ?? "—"}</td>
      <td class="mono ${n.rev_eps_pct >= 0 ? "spr-good" : "spr-bad"}">${n.rev_eps_pct >= 0 ? "+" : ""}${n.rev_eps_pct}%</td>
      <td class="mono">${n.rev_receita_pct === null ? "—" : (n.rev_receita_pct >= 0 ? "+" : "") + n.rev_receita_pct + "%"}</td>
      <td class="mono">${n.eps_ini} &rarr; ${n.eps_fim}</td>
      <td class="mono">${n.n_analistas ?? "—"}</td></tr>`;
    const tabela = (ns, rot, cls) => `<h4 class="eq-sub ${cls}">${rot} <span>${ns.length}</span></h4>
      <div class="table-wrap"><table class="data-table"><thead><tr>
        <th>Name</th><th>Sector</th><th>Price</th><th>EPS revision</th><th>Revenue revision</th>
        <th>EPS before &rarr; after</th><th>Analysts</th></tr></thead>
        <tbody>${ns.map(linha).join("")}</tbody></table></div>`;
    const set = (d.setores || []).slice().sort((a, b) => b.rev_mediana - a.rev_mediana);
    return `<div class="section-title" style="margin-top:30px">
        <div><h2>Earnings revisions</h2></div>
        <p>What analysts changed their minds about between two point-in-time snapshots.</p>
      </div>
      <p class="method-note">${esc(d.metodo || "")}<br><em>${esc(d.limite || "")}</em><br>
        Window ${esc(d.janela || "")} · ${d.n_tickers} names ·
        median ${d.estatistica?.mediana}% · ${d.estatistica?.subiram} up / ${d.estatistica?.cairam} down ·
        generated ${esc(d.gerado_em || "")}.</p>
      <div class="eq-setores">${set.map((x) => `<span class="eq-set ${x.rev_mediana >= 0 ? "eq-set-up" : "eq-set-dn"}">
        ${esc(x.setor)} <b>${x.rev_mediana >= 0 ? "+" : ""}${x.rev_mediana}%</b>
        <i>${x.pct_subindo}% up · n=${x.n}</i></span>`).join("")}</div>
      ${tabela(d.cima, "Revised up", "eq-sub-ok")}
      ${tabela(d.baixo, "Revised down", "eq-sub-no")}`;
  }

  async function renderCards() {
    const alvo = document.getElementById("sentinelaBody");
    if (!alvo) return;
    await fichas();                       // sem isto os cards saem sem fonte
    // Fornecedores voltou: sumiu quando o despejo de texto saiu, porque so existia como <pre>.
    const forn = await bloco("fornecedores.json", "Strategic suppliers",
      "Suppliers to the giants — semis, datacenter, energy, water, health, defence. Drops in names with a registered thesis.",
      "fornecedores", ["Com gatilho", "Sem setup"]);
    const dv = await bloco("deep_value_scan.json", "Deep Value",
      "Genuinely cheap, screened against the value trap.",
      "deep-value", ["Candidatos para análise", "Reprovados pela peneira"]);
    const btd = await bloco("btd_scan.json", "BTD + HOLD",
      "Today’s drop in a quality name — separating market fear from a company problem.",
      "btd", ["Com gatilho", "Sem setup"]);
    const rev = await blocoRevisoes();
    const html = forn + dv + btd + rev;
    if (html) alvo.insertAdjacentHTML("beforeend", html);
  }

  document.addEventListener("DOMContentLoaded", render);
  const bar = document.getElementById("tabBar");
  if (bar) bar.addEventListener("click", (e) => {
    const b = e.target.closest(".tab");
    if (b && b.dataset.tab === "equities") render();
  });
})();
